on:
  pull_request:
  push:
    branches:
      - main
      - release
jobs:
  test:
    runs-on: ubuntu-latest
    name: testing and linting this branch
    steps:
      - name: check out this repo
        uses: actions/checkout@v6
      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: lint bun
        run: |
          bun i
          bun run oxfmt --check
      - name: lint java
        run: |
          curl -L -o /tmp/gvf https://github.com/google/google-java-format/releases/download/v1.36.1/google-java-format_linux-x86-64
          chmod u+x /tmp/gvf
          git ls-files | grep '\.java$' | xargs /tmp/gvf -i
          git status -s 2>/dev/null | python3 -c "import sys; sys.exit(0 if len(sys.stdin.read()) == 0 else 1)"
      - name: check for TODO string instances
        run: |
          git ls-files | grep -v test-branch\.yml | xargs grep -Ii todo | wc -l | xargs python3 -c "import sys; sys.exit(0 if int(sys.argv[1]) == 0 else 1)"
      - name: run assignments
        run: |
          make run
